name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4


      # Python环境
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"


      # 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller


      # 安装 Inno Setup
      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress -y


      # 执行你的打包脚本
      - name: Build DesktopWidget
        env:
          ISCC_PATH: iscc.exe
          BUILD_ARCHIVE_DIR: ${{ github.workspace }}\archives

        run: |
          python tools/build.py 1.3.3


      # 上传安装包
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: DesktopWidget-installer
          path: |
            dist/*.exe